### ISSUE TITLE
bioconductor release / princurve

### ISSUE THREAD

**Issue by rcannood** [HenrikBengtsson/aroma.light#16]
Hey Henrik,

princurve 2.1.3 is on it's way to CRAN, and with it comes the deprecation of `get.lam()` and `principal.curve()`. 

I just noticed aroma.light on the bioconductor release is still using princurve 1.1, so some deprecation warnings will get generated when or if bioconductor decides to rebuild.

Robrecht

**Comment by HenrikBengtsson** [comment]
Thanks for this heads up.

So, [aroma.light 3.11.2](http://bioconductor.org/packages/devel/bioc/html/aroma.light.html) (2018-09-04), which is in the Bioc developer branch (to become Bioconductor 3.8), requires princurve (>= 2.1.2) and uses `princurve::principal_curve()` internally.  The Bioc devel branch will become Bioconductor 3.8 on 2018-10-31 (9 days from now).

When Bioconductor 3.8 is released, the current release version, Bioconductor 3.7, will become obsolete together with [aroma.light 3.10.0](http://bioconductor.org/packages/release/bioc/html/aroma.light.html), which I have not bothered backporting to princurve (>= 2.1.2).  Hence the:
```
* checking examples ... WARNING
Found the following significant warnings:

  Warning: 'principal.curve' is deprecated.
  Warning: 'principal.curve' is deprecated.
Deprecated functions may be defunct as soon as of the next release of R.
```
after your recent release of [princurve](https://cran.r-project.org/web/packages/princurve/) 2.1.3 (2018-10-08).  Assuming you won't **defunct** anything before Bioc 3.8, I will not spend time fixing the Bioc release of aroma.light.  Is that alright with your plans?

**Comment by rcannood** [comment]
Good to hear :) :+1: Thanks
